import { expect, test } from '@playwright/test';
import { readFile } from 'node:fs/promises';

test('placement, editing, undo, and file round-trip work in the rendered editor', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.locator('canvas')).toBeVisible();
  await expect(page.locator('#object-count')).not.toHaveText('0');
  await page.screenshot({ path: 'test-results/layout-desktop.png' });
  const initialCount = Number(await page.locator('#object-count').textContent());
  await page.getByRole('button', { name: '위에서', exact: true }).click();
  await page.getByRole('button', { name: '주거동 배치', exact: true }).click();
  const canvas = page.locator('canvas');
  const rect = (await canvas.boundingBox())!;
  // Use empty ground; the center of the demo contains paths and stairs.
  await canvas.click({ position: { x: rect.width / 2 + 230, y: rect.height / 2 + 230 } });
  await expect(page.locator('#object-count')).toHaveText(String(initialCount + 1));
  await page.keyboard.press('Escape');
  await canvas.click({ position: { x: rect.width / 2 + 240, y: rect.height / 2 + 240 } });
  await page.getByRole('spinbutton', { name: 'X 좌표', exact: true }).fill('5');
  await page.getByRole('spinbutton', { name: 'X 좌표', exact: true }).press('Tab');
  await expect(page.getByRole('spinbutton', { name: 'X 좌표', exact: true })).toHaveValue('5');
  await page.getByRole('button', { name: '90° 회전 R' }).click();
  await expect(page.locator('.rotation-row > span')).toHaveText('90°');
  await page.getByRole('button', { name: '삭제', exact: true }).click();
  await expect(page.locator('#object-count')).toHaveText(String(initialCount));
  await page.getByRole('button', { name: '실행 취소', exact: true }).click();
  await expect(page.locator('#object-count')).toHaveText(String(initialCount + 1));
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: '청사진 저장', exact: true }).click();
  const download = await downloadPromise;
  const data = JSON.parse(await readFile((await download.path())!, 'utf8'));
  expect(data.catalogProfile).toBe('layout-demo');
  expect(data.objects.at(-1).position.x).toBe(5);
  expect(data.objects.at(-1).rotation).toBe(90);
  data.name = '에이전트가 편집한 청사진';
  data.objects.at(-1).position.x = 7;
  await page.locator('#file-input').setInputFiles({ name: 'edited.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(data)) });
  await expect(page.getByRole('textbox', { name: '청사진 이름' })).toHaveValue(data.name);
  await page.reload();
  await expect(page.getByRole('textbox', { name: '청사진 이름' })).toHaveValue(data.name);
  expect(errors).toEqual([]);
});

test('floor display, factions, invalid imports, and compact layout', async ({ page }) => {
  await page.goto('/');
  await expect(page.locator('canvas')).toBeVisible();
  const before = await page.locator('canvas').screenshot();
  await page.locator('#cutaway').check();
  await expect(page.locator('#view-caption')).toHaveText('0층 이하 표시');
  const after = await page.locator('canvas').screenshot();
  expect(before.equals(after)).toBe(false);
  await page.getByRole('button', { name: '배치 높이 올리기', exact: true }).click();
  await expect(page.getByRole('spinbutton', { name: '배치 높이', exact: true })).toHaveValue('1');
  const name = page.getByRole('textbox', { name: '청사진 이름' });
  await name.fill('보관할 폴크테일 설계');
  await name.press('Tab');
  await page.getByRole('button', { name: 'Iron Teeth', exact: true }).click();
  await expect(name).toHaveValue('첫 번째 메가시티');
  await page.getByRole('button', { name: 'Folktails', exact: true }).click();
  await expect(name).toHaveValue('보관할 폴크테일 설계');
  await page.locator('#file-input').setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{}') });
  await expect(page.locator('#toast')).toContainText('지원하는 청사진 파일이 아닙니다');
  await expect(name).toHaveValue('보관할 폴크테일 설계');
  await expect(page.locator('#toast')).not.toHaveClass(/visible/);
  await page.setViewportSize({ width: 960, height: 800 });
  await expect(page.locator('.inspector')).not.toBeVisible();
  await page.getByRole('button', { name: '속성 패널 접기 / 펼치기' }).click();
  await expect(page.locator('.inspector')).toBeVisible();
  await page.getByRole('button', { name: '속성 패널 접기 / 펼치기' }).click();
  await expect(page.locator('.inspector')).not.toBeVisible();
  await expect(page.locator('body')).toHaveJSProperty('scrollWidth', 960);
  await page.screenshot({ path: 'test-results/layout-compact.png' });
  await page.setViewportSize({ width: 600, height: 800 });
  await expect(page.locator('body')).toHaveJSProperty('scrollWidth', 600);
  await page.screenshot({ path: 'test-results/layout-narrow.png' });
});
